"""
app.py

Interactive Streamlit dashboard visualizing structured data extracted 
from UN Human Development Reports via local LLM pipelines.
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json

# ==========================================
# CONFIGURATION & DATA LOADING
# ==========================================
st.set_page_config(page_title="Zambia Development Analysis", page_icon="🇿🇲", layout="wide")
sns.set_theme(style="whitegrid", palette="muted")

@st.cache_data
def load_data(filepath="extracted_data.json"):
    """Reads the JSON output generated by the LLM pipeline."""
    try:
        with open(filepath, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        return None

# ==========================================
# VISUALIZATION FUNCTIONS
# ==========================================
def plot_thematic_distribution(themes_dict):
    """Renders a horizontal bar chart of thematic frequency."""
    theme_df = pd.DataFrame(list(themes_dict.items()), columns=['Theme', 'Mentions'])
    theme_df = theme_df.sort_values(by='Mentions', ascending=False)
    
    fig, ax = plt.subplots(figsize=(6, 4))
    sns.barplot(data=theme_df, x='Mentions', y='Theme', ax=ax, palette="viridis")
    ax.set_xlabel("Frequency Focus Score")
    ax.set_ylabel("")
    return fig

def plot_model_comparison(comp_data):
    """Renders a grouped bar chart comparing ground truth vs LLM outputs."""
    comp_df = pd.DataFrame(comp_data)
    melted_df = comp_df.melt(id_vars="Indicators", var_name="Model/Source", value_name="Value")
    
    fig, ax = plt.subplots(figsize=(6, 4))
    sns.barplot(data=melted_df, x="Indicators", y="Value", hue="Model/Source", ax=ax, palette="Set2")
    ax.set_yscale("log") # Log scale required due to magnitude variations in indicators
    ax.set_ylabel("Values (Log Scale)")
    ax.set_xlabel("")
    plt.xticks(rotation=15)
    return fig

def plot_hdi_trend(trend_dict):
    """Renders a line plot showing historical HDI progression."""
    hdi_df = pd.DataFrame(list(trend_dict.items()), columns=['Year', 'HDI'])
    hdi_df['Year'] = pd.to_numeric(hdi_df['Year'])
    hdi_df = hdi_df.sort_values('Year')
    
    fig, ax = plt.subplots(figsize=(6, 4))
    sns.lineplot(data=hdi_df, x='Year', y='HDI', marker='o', linewidth=2.5, color='royalblue', ax=ax)
    ax.set_ylim(0, 1)
    ax.set_ylabel("Human Development Index Score")
    return fig

def plot_population_trend(pop_dict):
    """Renders an area chart showing demographic growth."""
    pop_df = pd.DataFrame(list(pop_dict.items()), columns=['Year', 'Population (Millions)'])
    pop_df['Year'] = pd.to_numeric(pop_df['Year'])
    pop_df = pop_df.sort_values('Year')
    
    fig, ax = plt.subplots(figsize=(6, 4))
    sns.lineplot(data=pop_df, x='Year', y='Population (Millions)', marker='s', linewidth=2.5, color='forestgreen', ax=ax)
    ax.fill_between(pop_df['Year'], pop_df['Population (Millions)'], color='forestgreen', alpha=0.1)
    ax.set_ylabel("Total Population (Millions)")
    return fig

# ==========================================
# MAIN DASHBOARD LAYOUT
# ==========================================
def main():
    st.title("📊 Zambia Development Analytics Portal")
    st.markdown("An interactive platform for evaluating key human development indicators and cross-LLM extraction accuracy.")

    app_data = load_data()

    if not app_data:
        st.error("Data source missing. Please run `python pipeline.py` to generate the JSON dataset.")
        return

    data = app_data["data"]
    evaluation = app_data["evaluation"]
    
    # 1. CORE KPI METRICS
    st.subheader("Core Development Indicators")
    col1, col2, col3, col4, col5 = st.columns(5)
    col1.metric("HDI Value", data.get('HDI_value', 'N/A'))
    col2.metric("HDI Rank", data.get('HDI_rank', 'N/A'))
    col3.metric("Life Expectancy", f"{data.get('life_expectancy_years', 'N/A')} yrs")
    col4.metric("Schooling (Expected)", f"{data.get('expected_years_of_schooling', 'N/A')} yrs")
    col5.metric("GNI per Capita", f"${data.get('GNI_per_capita', 'N/A')}")
    st.markdown("---")
    
    # 2. VISUAL ANALYTICS (4 PLOTS)
    row1_col1, row1_col2 = st.columns(2)
    with row1_col1:
        st.subheader("1. Thematic Extraction Distribution")
        if data.get('themes'): st.pyplot(plot_thematic_distribution(data['themes']))
            
    with row1_col2:
        st.subheader("2. Model Comparison of Numerical Indicators")
        if data.get('model_comparison'): st.pyplot(plot_model_comparison(data['model_comparison']))

    st.markdown("---")
    
    row2_col1, row2_col2 = st.columns(2)
    with row2_col1:
        st.subheader("3. Historical HDI Trend")
        if data.get('hdi_trend'): st.pyplot(plot_hdi_trend(data['hdi_trend']))
            
    with row2_col2:
        st.subheader("4. Demographic Trend (Population Growth)")
        if data.get('population_trend'): st.pyplot(plot_population_trend(data['population_trend']))

    st.markdown("---")

    # 3. QUALITATIVE INSIGHTS & EVALUATION
    st.subheader("Qualitative Narrative Insights")
    qual_col1, qual_col2 = st.columns(2)
    with qual_col1:
        st.info("**Key Strategic Strengths:**")
        for strength in data.get('key_strengths', []): st.markdown(f"- {strength}")
            
    with qual_col2:
        st.warning("**Key Strategic Challenges:**")
        for challenge in data.get('key_challenges', []): st.markdown(f"- {challenge}")

    st.markdown("---")
    st.subheader("Evaluation & Cross-LLM Behavior Analysis")
    st.write(evaluation)

if __name__ == "__main__":
    main()
